openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ericryanbowser/AssistApi/1.0.0
  - description: HTTPs
    url: https://localhost:3001
info:
  description: Node.js Assistant API with Vectors
  version: "1.0.0"
  title: Node Assist API
  contact:
    email: ericryanbowser@gmail.com
  license:
    name: MIT
paths:
  /askAssist:
    post:
      summary: Text Question
      operationId: assist
      description: Ask assistant a question
      responses:
        '200':
          description: Returns an answer
          content:
            application/json:
              schema:
                type: object
        '400':
          description: bad request
      parameters:
        - name: content
          in: query
          description: Question to ask
          required: true
          schema:
            type: string