openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ericryanbowser/AssistApi/1.0.0
  - description: HTTPs
    url: https://localhost:5002
info:
  description: Node.js Assistant API with Vectors
  version: "1.0.0"
  title: Node Assist API
  contact:
    email: ericryanbowser@gmail.com
  license:
    name: MIT
paths:
  /generalAssist:
    post:
      summary: get assistant
      operationId: assist
      description: Retrieve Assistant
      responses:
        '200':
          description: Returns an assistant object / model
          content:
            application/json:
              schema:
                type: string
        '400':
          description: ApiKey is not recognized
  /enablePgVector:
    post:
      summary: enable pgvector type
      operationId: enablePgvector
      description: enable pgvector type for postgreSQL database
      parameters: []
      responses:
        '200':
          description: creates type effectively 
          content: 
            application/json:
              schema:
                type: string
        '400':
          description: ApiKey is not recognized